name: Deploy to production - Frontend Service

on:
  workflow_dispatch:
    inputs:
      version_frontend:
        description: 'Enter version to deploy'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test 
        run: echo "${{ github.event.inputs.version_frontend }}"